/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Timestamp = IDL.Int;
export const Person = IDL.Record({
  'dob' : IDL.Opt(IDL.Text),
  'tob' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Text,
  'dob' : IDL.Opt(IDL.Text),
  'tob' : IDL.Opt(IDL.Text),
  'palmPhotos' : IDL.Vec(IDL.Opt(ExternalBlob)),
  'question' : IDL.Text,
  'authorId' : IDL.Opt(IDL.Principal),
  'seedNumber' : IDL.Opt(IDL.Nat),
  'city' : IDL.Opt(IDL.Text),
  'submittedAt' : Timestamp,
  'birthCountry' : IDL.Opt(IDL.Text),
  'handPicture' : IDL.Opt(ExternalBlob),
  'state' : IDL.Opt(IDL.Text),
  'visitorName' : IDL.Text,
  'pastLifeNotes' : IDL.Text,
  'serviceId' : IDL.Nat,
  'relationshipPerson2' : IDL.Opt(Person),
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : Timestamp,
  'author' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'price' : IDL.Nat,
});
export const Notice = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'createdAt' : Timestamp,
  'message' : IDL.Text,
});
export const NumerologyUser = IDL.Record({
  'username' : IDL.Text,
  'passwordHash' : IDL.Text,
  'sectionLevel' : IDL.Nat,
});
export const VisitorID = IDL.Record({
  'service' : IDL.Text,
  'expiresAt' : Timestamp,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'createdAt' : Timestamp,
  'visitorName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'deleteInquiry' : IDL.Func([IDL.Text], [], []),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllPostsAdmin' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'noticeCreate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'noticeDelete' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'noticeList' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'noticeListAll' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Notice)],
      ['query'],
    ),
  'noticeToggleActive' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'numerologyCreateUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'numerologyDeleteUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'numerologyListUsers' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(NumerologyUser)],
      ['query'],
    ),
  'numerologyLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'publishPost' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitInquiry' : IDL.Func([Inquiry], [IDL.Text], []),
  'updatePost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'visitorCreateId' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'visitorDeleteId' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'visitorListIds' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(VisitorID)],
      ['query'],
    ),
  'visitorValidateId' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Timestamp = IDL.Int;
  const Person = IDL.Record({
    'dob' : IDL.Opt(IDL.Text),
    'tob' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Text,
    'dob' : IDL.Opt(IDL.Text),
    'tob' : IDL.Opt(IDL.Text),
    'palmPhotos' : IDL.Vec(IDL.Opt(ExternalBlob)),
    'question' : IDL.Text,
    'authorId' : IDL.Opt(IDL.Principal),
    'seedNumber' : IDL.Opt(IDL.Nat),
    'city' : IDL.Opt(IDL.Text),
    'submittedAt' : Timestamp,
    'birthCountry' : IDL.Opt(IDL.Text),
    'handPicture' : IDL.Opt(ExternalBlob),
    'state' : IDL.Opt(IDL.Text),
    'visitorName' : IDL.Text,
    'pastLifeNotes' : IDL.Text,
    'serviceId' : IDL.Nat,
    'relationshipPerson2' : IDL.Opt(Person),
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : Timestamp,
    'author' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Notice = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'createdAt' : Timestamp,
    'message' : IDL.Text,
  });
  const NumerologyUser = IDL.Record({
    'username' : IDL.Text,
    'passwordHash' : IDL.Text,
    'sectionLevel' : IDL.Nat,
  });
  const VisitorID = IDL.Record({
    'service' : IDL.Text,
    'expiresAt' : Timestamp,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'createdAt' : Timestamp,
    'visitorName' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'deleteInquiry' : IDL.Func([IDL.Text], [], []),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllPostsAdmin' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'noticeCreate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'noticeDelete' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'noticeList' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'noticeListAll' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Notice)],
        ['query'],
      ),
    'noticeToggleActive' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'numerologyCreateUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'numerologyDeleteUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'numerologyListUsers' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(NumerologyUser)],
        ['query'],
      ),
    'numerologyLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'publishPost' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitInquiry' : IDL.Func([Inquiry], [IDL.Text], []),
    'updatePost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'visitorCreateId' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'visitorDeleteId' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'visitorListIds' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(VisitorID)],
        ['query'],
      ),
    'visitorValidateId' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };